### ISSUE TITLE
Release packages

### ISSUE THREAD

**Issue by ijnek** [ros-sports/rcss3d_agent#13]
Couldn't proceed due to errors in bloom, see error note at bottom:

- [x] galactic
  - [x] catkin_generate_changelog
  - [x] catkin_prepare_release
  - [x] bloom-release
- [x] humble
  - [x] catkin_generate_changelog
  - [x] catkin_prepare_release
  - [x] bloom-release
- [x] rolling
  - [x] catkin_generate_changelog
  - [x] catkin_prepare_release
  - [x] bloom-release

Error when running ``bloom-release``:

```
==> git-bloom-generate -y rosrpm --prefix release/rolling rolling -i 1 --os-name rhel
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Generating source RPMs for the packages: ['rcss3d_agent_msgs', 'rcss3d_agent', 'rcss3d_agent_basic']
RPM Incremental Version: 1
RPM OS: rhel
RPM Distributions: ['8']
Releasing for rosdistro: rolling

Pre-verifying RPM dependency keys...
Running 'rosdep update'...
ROS Distro index file associate with commit '353fc59095aabbf8b2129967c3ed961c5b5d7c4f'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/353fc59095aabbf8b2129967c3ed961c5b5d7c4f/index-v4.yaml'
All keys are OK

Placing RPM template files into 'rpm/rolling/rcss3d_agent_msgs' branch.
==> Placing templates files in the 'rpm' folder.

####
#### Generating 'rhel 8' RPM for package 'rcss3d_agent_msgs' at version '0.3.1-1'
####
Generating RPM for rhel 8...
No homepage set
Package 'rcss3d-agent-msgs' has dependencies:
Run Dependencies:
  rosdep key           => rhel 8 key
  builtin_interfaces   => ['ros-rolling-builtin-interfaces']
  rosidl_default_runtime => ['ros-rolling-rosidl-default-runtime']
Build and Build Tool Dependencies:
  rosdep key           => rhel 8 key
  builtin_interfaces   => ['ros-rolling-builtin-interfaces']
  rosidl_default_generators => ['ros-rolling-rosidl-default-generators']
  ament_cmake          => ['ros-rolling-ament-cmake']
==> In place processing templates in 'rpm' folder.
Expanding 'rpm/template.spec.em' -> 'rpm/template.spec'
'execute_command' failed to call 'git mv rpm/template.spec rpm/ros-rolling-rcss3d-agent-msgs.spec' which had a return code (128):
'''
fatal: not under version control, source=rpm/template.spec, destination=rpm/ros-rolling-rcss3d-agent-msgs.spec

'''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bloom/commands/git/generate.py", line 101, in try_execute
    retcode = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/bloom/generators/rpm/generator.py", line 672, in post_rebase
    data = self.generate_rpm(package, distro)
  File "/usr/lib/python3/dist-packages/bloom/generators/rpm/generator.py", line 808, in generate_rpm
    execute_command('git mv ' + rpm_dir + '/template.spec ' + rpm_dir + '/' + subs['Package'] + '.spec')
  File "/usr/lib/python3/dist-packages/bloom/util.py", line 462, in execute_command
    raise CalledProcessError(result, cmd)
subprocess.CalledProcessError: Command 'git mv rpm/template.spec rpm/ros-rolling-rcss3d-agent-msgs.spec' returned non-zero exit status 128.

Error calling generator post_rebase: Command 'git mv rpm/template.spec rpm/ros-rolling-rcss3d-agent-msgs.spec' returned non-zero exit status 128.
generator post_rebase returned exit code (128)
<== Error running command '['/usr/bin/git-bloom-generate', '-y', 'rosrpm', '--prefix', 'release/rolling', 'rolling', '-i', '1', '--os-name', 'rhel']'
Release failed, exiting.
```

**Comment by ijnek** [comment]
The error was caused due to this: https://github.com/ros-infrastructure/bloom/issues/680
Managed to proceed with releasing.

**Comment by ijnek** [comment]
Closing this, as PRs have been raised to rosdistro.
